services:
    ag_geocoding.shared_storage:
        class: Keboola\GeocodingBundle\Service\SharedStorage
        arguments: [@doctrine]
    ag_geocoding.job_executor:
        class: Keboola\GeocodingBundle\JobExecutor
        arguments: [@ag_geocoding.shared_storage, @syrup.temp, @logger, %google_key%, %mapquest_key%]
