branches:
  only:
    - master

sudo: false

language: php
php:
  - '5.4'
services:
  - mysql

before_script:
  - mysql -e 'create database ag_geocoding_test;'
  - composer self-update
  - composer install -n --no-scripts
script:
  - ./vendor/bin/phpcs --standard=psr2 -n --ignore=vendor .
  - ./vendor/bin/phpunit
after_script:
  - ./codeclimate.sh
notifications:
  slack:
    secure: ZwEGJBi9LNocVYWbDMu5llfTxQ9UHQCbAEiGr8RsXFgALRXvYQ4Ymw2GfLGMdFAaZ55SSeTsDHa4btJ2LFWMi+r+anDN4oWDxfjtY2pdpB7lQh19PhjSKYGz59e7vX8x3iPmygMbcPFW6Bee9n8yVW9/Md6JxgBIRcoVratFyks=
