branches:
  only:
    - master

language: php
php:
  - '5.6'
  - '5.4'
services:
  - mysql

before_script:
  - mysql -e 'create database ag_forecastio_test;'
  - composer install -n --no-scripts

notifications:
  slack:
    secure: ZwEGJBi9LNocVYWbDMu5llfTxQ9UHQCbAEiGr8RsXFgALRXvYQ4Ymw2GfLGMdFAaZ55SSeTsDHa4btJ2LFWMi+r+anDN4oWDxfjtY2pdpB7lQh19PhjSKYGz59e7vX8x3iPmygMbcPFW6Bee9n8yVW9/Md6JxgBIRcoVratFyks=
