version: "2"

services:

  tests:
    build: .
    image: keboola/geocoding-augmentation
    tty: true
    stdin_open: true
    command: ./tests.sh

  dev:
    image: keboola/geocoding-augmentation
    tty: true
    stdin_open: true
    command: ./tests.sh
    volumes:
     - .:/code

  tests-with-report:
    extends:
      service: tests
    volumes:
      - ./.git:/code/.git
    command: sh -c './tests.sh && ./vendor/bin/test-reporter'