version: "2"

services:

  tests:
    build: .
    image: keboola/geocoding-augmentation
    tty: true
    stdin_open: true
    command: ./tests.sh
    environment:
      - GOOGLE_MAPS_API_KEY

  dev:
    build: .
    image: keboola/geocoding-augmentation
    tty: true
    stdin_open: true
    command: ./tests.sh
    volumes:
     - .:/code
